on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build and push
        run: |
          APIKEY="${{ secrets.HOG_NUGET }}"
          IFS=. read -r v1 v2 v3 <<< $(cat ./VERSION)
          v3=$((v3 + 1))
          VERSION="$v1.$v2.$v3"
          echo "Building version: *$VERSION*"
          dotnet pack --configuration Release --include-source --output . /p:Version="$VERSION" Frends.HIT.PushDoc/Frends.HIT.PushDoc.csproj
          dotnet nuget push "Frends.HIT.PushDoc.$VERSION.nupkg" --source https://proget.hoglan.dev/nuget/Frends/ --api-key "$APIKEY"
          echo "$VERSION" > VERSION
          rm -f ./Frends.HIT.PushDoc.*.nupkg
          git config user.email "autopush@hoglan.dev"
          git config user.name "AutoPush"
          git add VERSION
          git commit -m "[AUTO] Increment version number"
          git push origin main
          echo "Done"